const fs = require('fs');
const path = require('path');

const outfitsDir = path.join(__dirname, '..', 'public', 'outfits');
const dirs = fs.readdirSync(outfitsDir).filter(f => fs.statSync(path.join(outfitsDir, f)).isDirectory());

const result = {};

for (const dir of dirs) {
  if (dir === 'garments') continue;
  const dirPath = path.join(outfitsDir, dir);
  const files = fs.readdirSync(dirPath).filter(file => {
    return file.endsWith('.jpeg') || file.endsWith('.jpg') || file.endsWith('.png');
  });
  result[dir] = files.map(file => `/outfits/${dir}/${file}`);
}

const content = `// This file is auto-generated by scripts/generateOutfitImages.cjs. Do not edit directly.
export const OUTFIT_IMAGES: Record<string, string[]> = ${JSON.stringify(result, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'data', 'outfitImages.ts'), content);
console.log('Successfully generated outfit images list.');
