// This file is auto-generated by scripts/generateOutfitImages.cjs. Do not edit directly.
export const OUTFIT_IMAGES: Record<string, string[]> = {
  "Boho Men": [
    "/outfits/Boho Men/WhatsApp Image 2026-07-16 at 10.04.21 PM (1).jpeg",
    "/outfits/Boho Men/WhatsApp Image 2026-07-16 at 10.04.21 PM (2).jpeg",
    "/outfits/Boho Men/WhatsApp Image 2026-07-16 at 10.04.21 PM (3).jpeg",
    "/outfits/Boho Men/WhatsApp Image 2026-07-16 at 10.04.21 PM.jpeg",
    "/outfits/Boho Men/WhatsApp Image 2026-07-16 at 10.04.22 PM (1).jpeg",
    "/outfits/Boho Men/WhatsApp Image 2026-07-16 at 10.04.22 PM.jpeg"
  ],
  "Boho Women": [
    "/outfits/Boho Women/WhatsApp Image 2026-07-16 at 10.04.12 PM (1).jpeg",
    "/outfits/Boho Women/WhatsApp Image 2026-07-16 at 10.04.12 PM.jpeg",
    "/outfits/Boho Women/WhatsApp Image 2026-07-16 at 10.04.13 PM (1).jpeg",
    "/outfits/Boho Women/WhatsApp Image 2026-07-16 at 10.04.13 PM (2).jpeg",
    "/outfits/Boho Women/WhatsApp Image 2026-07-16 at 10.04.13 PM (3).jpeg",
    "/outfits/Boho Women/WhatsApp Image 2026-07-16 at 10.04.13 PM.jpeg"
  ],
  "Clean Girl": [
    "/outfits/Clean Girl/WhatsApp Image 2026-07-16 at 10.03.57 PM (1).jpeg",
    "/outfits/Clean Girl/WhatsApp Image 2026-07-16 at 10.03.57 PM (2).jpeg",
    "/outfits/Clean Girl/WhatsApp Image 2026-07-16 at 10.03.57 PM.jpeg",
    "/outfits/Clean Girl/WhatsApp Image 2026-07-16 at 10.03.58 PM (1).jpeg",
    "/outfits/Clean Girl/WhatsApp Image 2026-07-16 at 10.03.58 PM (2).jpeg",
    "/outfits/Clean Girl/WhatsApp Image 2026-07-16 at 10.03.58 PM.jpeg"
  ],
  "Coquette": [
    "/outfits/Coquette/WhatsApp Image 2026-07-16 at 10.24.35 PM.jpeg",
    "/outfits/Coquette/WhatsApp Image 2026-07-16 at 10.24.36 PM (1).jpeg",
    "/outfits/Coquette/WhatsApp Image 2026-07-16 at 10.24.36 PM (2).jpeg",
    "/outfits/Coquette/WhatsApp Image 2026-07-16 at 10.24.36 PM.jpeg",
    "/outfits/Coquette/WhatsApp Image 2026-07-16 at 10.24.37 PM (1).jpeg",
    "/outfits/Coquette/WhatsApp Image 2026-07-16 at 10.24.37 PM.jpeg"
  ],
  "Cottage Core Men": [
    "/outfits/Cottage Core Men/WhatsApp Image 2026-07-16 at 10.40.01 PM (1).jpeg",
    "/outfits/Cottage Core Men/WhatsApp Image 2026-07-16 at 10.40.01 PM (2).jpeg",
    "/outfits/Cottage Core Men/WhatsApp Image 2026-07-16 at 10.40.01 PM (3).jpeg",
    "/outfits/Cottage Core Men/WhatsApp Image 2026-07-16 at 10.40.01 PM.jpeg",
    "/outfits/Cottage Core Men/WhatsApp Image 2026-07-16 at 10.40.02 PM (1).jpeg",
    "/outfits/Cottage Core Men/WhatsApp Image 2026-07-16 at 10.40.02 PM.jpeg"
  ],
  "Cottage Core Women": [
    "/outfits/Cottage Core Women/WhatsApp Image 2026-07-16 at 10.39.50 PM.jpeg",
    "/outfits/Cottage Core Women/WhatsApp Image 2026-07-16 at 10.39.51 PM (1).jpeg",
    "/outfits/Cottage Core Women/WhatsApp Image 2026-07-16 at 10.39.51 PM (2).jpeg",
    "/outfits/Cottage Core Women/WhatsApp Image 2026-07-16 at 10.39.51 PM.jpeg",
    "/outfits/Cottage Core Women/WhatsApp Image 2026-07-16 at 10.39.52 PM (1).jpeg",
    "/outfits/Cottage Core Women/WhatsApp Image 2026-07-16 at 10.39.52 PM.jpeg"
  ],
  "Dark Academia Men": [
    "/outfits/Dark Academia Men/WhatsApp Image 2026-07-16 at 10.03.39 PM (1).jpeg",
    "/outfits/Dark Academia Men/WhatsApp Image 2026-07-16 at 10.03.39 PM.jpeg",
    "/outfits/Dark Academia Men/WhatsApp Image 2026-07-16 at 10.03.40 PM (1).jpeg",
    "/outfits/Dark Academia Men/WhatsApp Image 2026-07-16 at 10.03.40 PM (2).jpeg",
    "/outfits/Dark Academia Men/WhatsApp Image 2026-07-16 at 10.03.40 PM (3).jpeg",
    "/outfits/Dark Academia Men/WhatsApp Image 2026-07-16 at 10.03.40 PM.jpeg"
  ],
  "Dark Academia Women": [
    "/outfits/Dark Academia Women/WhatsApp Image 2026-07-16 at 10.03.25 PM.jpeg",
    "/outfits/Dark Academia Women/WhatsApp Image 2026-07-16 at 10.03.26 PM (1).jpeg",
    "/outfits/Dark Academia Women/WhatsApp Image 2026-07-16 at 10.03.26 PM (2).jpeg",
    "/outfits/Dark Academia Women/WhatsApp Image 2026-07-16 at 10.03.26 PM (3).jpeg",
    "/outfits/Dark Academia Women/WhatsApp Image 2026-07-16 at 10.03.26 PM.jpeg",
    "/outfits/Dark Academia Women/WhatsApp Image 2026-07-16 at 10.03.27 PM.jpeg"
  ],
  "Old Money Men": [
    "/outfits/Old Money Men/WhatsApp Image 2026-07-16 at 9.10.29 PM (1).jpeg",
    "/outfits/Old Money Men/WhatsApp Image 2026-07-16 at 9.10.29 PM (2).jpeg",
    "/outfits/Old Money Men/WhatsApp Image 2026-07-16 at 9.10.29 PM.jpeg",
    "/outfits/Old Money Men/WhatsApp Image 2026-07-16 at 9.10.30 PM (1).jpeg",
    "/outfits/Old Money Men/WhatsApp Image 2026-07-16 at 9.10.30 PM (2).jpeg",
    "/outfits/Old Money Men/WhatsApp Image 2026-07-16 at 9.10.30 PM.jpeg"
  ],
  "Old Money Women": [
    "/outfits/Old Money Women/WhatsApp Image 2026-07-16 at 9.10.09 PM (1).jpeg",
    "/outfits/Old Money Women/WhatsApp Image 2026-07-16 at 9.10.09 PM (2).jpeg",
    "/outfits/Old Money Women/WhatsApp Image 2026-07-16 at 9.10.09 PM.jpeg",
    "/outfits/Old Money Women/WhatsApp Image 2026-07-16 at 9.10.10 PM (1).jpeg",
    "/outfits/Old Money Women/WhatsApp Image 2026-07-16 at 9.10.10 PM (2).jpeg",
    "/outfits/Old Money Women/WhatsApp Image 2026-07-16 at 9.10.10 PM.jpeg"
  ],
  "Streetwear Men": [
    "/outfits/Streetwear Men/WhatsApp Image 2026-07-16 at 10.25.25 PM (1).jpeg",
    "/outfits/Streetwear Men/WhatsApp Image 2026-07-16 at 10.25.25 PM.jpeg",
    "/outfits/Streetwear Men/WhatsApp Image 2026-07-16 at 10.25.26 PM (1).jpeg",
    "/outfits/Streetwear Men/WhatsApp Image 2026-07-16 at 10.25.26 PM (2).jpeg",
    "/outfits/Streetwear Men/WhatsApp Image 2026-07-16 at 10.25.26 PM (3).jpeg",
    "/outfits/Streetwear Men/WhatsApp Image 2026-07-16 at 10.25.26 PM.jpeg"
  ],
  "Streetwear Women": [
    "/outfits/Streetwear Women/WhatsApp Image 2026-07-16 at 10.24.49 PM (1).jpeg",
    "/outfits/Streetwear Women/WhatsApp Image 2026-07-16 at 10.24.49 PM.jpeg",
    "/outfits/Streetwear Women/WhatsApp Image 2026-07-16 at 10.24.50 PM (1).jpeg",
    "/outfits/Streetwear Women/WhatsApp Image 2026-07-16 at 10.24.50 PM (2).jpeg",
    "/outfits/Streetwear Women/WhatsApp Image 2026-07-16 at 10.24.50 PM (3).jpeg",
    "/outfits/Streetwear Women/WhatsApp Image 2026-07-16 at 10.24.50 PM.jpeg"
  ],
  "Y2K Men": [
    "/outfits/Y2K Men/WhatsApp Image 2026-07-16 at 9.18.17 PM.jpeg",
    "/outfits/Y2K Men/WhatsApp Image 2026-07-16 at 9.18.18 PM (1).jpeg",
    "/outfits/Y2K Men/WhatsApp Image 2026-07-16 at 9.18.18 PM (2).jpeg",
    "/outfits/Y2K Men/WhatsApp Image 2026-07-16 at 9.18.18 PM.jpeg",
    "/outfits/Y2K Men/WhatsApp Image 2026-07-16 at 9.18.19 PM (1).jpeg",
    "/outfits/Y2K Men/WhatsApp Image 2026-07-16 at 9.18.19 PM.jpeg"
  ],
  "Y2K Women": [
    "/outfits/Y2K Women/WhatsApp Image 2026-07-16 at 9.10.38 PM (1).jpeg",
    "/outfits/Y2K Women/WhatsApp Image 2026-07-16 at 9.10.38 PM.jpeg",
    "/outfits/Y2K Women/WhatsApp Image 2026-07-16 at 9.10.39 PM.jpeg",
    "/outfits/Y2K Women/WhatsApp Image 2026-07-16 at 9.10.40 PM (1).jpeg",
    "/outfits/Y2K Women/WhatsApp Image 2026-07-16 at 9.10.40 PM (2).jpeg",
    "/outfits/Y2K Women/WhatsApp Image 2026-07-16 at 9.10.40 PM.jpeg"
  ]
};
